---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1549909/sentiong/
    - /bin/cp -R .git $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp phpunit.xml.dist $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp spark $DEPLOYPATH

    - export DEPLOYPATH=/home/u1549909/public_html/
    - /bin/cp -R template $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
