---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1549909/sentiong/
    - /bin/cp -R .git $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH

deployment:
  tasks:
    - export DEPLOYPATH=/home/u1549909/public_html/
    - /bin/cp -R public/template $DEPLOYPATH
